version: "3.7"
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on: [rabbitmq, mongo_db]
  #   networks:
  #     net-10.9.0.0:
  #       ipv4_address: 10.9.0.4
  backend1:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.4
    depends_on:
      - db
      - cache
      - rabbitmq

  backend2:
    build: ./backend
    ports:
      - "9000:8000"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    depends_on:
      - db
      - cache
      - rabbitmq

  load_balancer:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.8

  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.9
  db:
    build: ./db
    ports:
      - "27017:27017"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3

  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.10
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
